name: Basic CI 3

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate code
        run: echo "Validating code changes"
      - name: Check formatting
        run: echo "Checking code formatting"