name: Basic CI 8

on:
  push:
    paths:
      - 'src/**'
      - '*.md'

jobs:
  docs-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build documentation
        run: echo "Building documentation"
      - name: Deploy docs
        run: echo "Deploying documentation"