name: Basic CI 4

on:
  push:
    branches: [ main, develop ]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Quality check
        run: echo "Running quality checks"
      - name: Security scan
        run: echo "Running security scan"