name: Basic CI 10

on:
  push:
    tags:
      - 'v*'

jobs:
  tag-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build tagged version
        run: echo "Building tagged version ${{ github.ref_name }}"
      - name: Create release notes
        run: echo "Creating release notes"