name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: echo "npm install"
      - name: Run tests with coverage
        run: echo "npm run test:coverage"
      - name: Upload coverage reports
        run: echo "Uploading coverage reports"