name: Container Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: echo "docker build -t myapp:latest ."
      - name: Test Docker image
        run: echo "docker run --rm myapp:latest echo 'Container test'"
      - name: Push to registry
        run: echo "Pushing image to registry"