name: Create Draft PR

on:
  issues:
    types: [assigned]

jobs:
  create_draft_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git user
        run: |
          git config --global user.email "deolube@github.com"
          git config --global user.name "DeoluBe"

      - name: Create placeholder commit
        run: |
          ISSUE_NUMBER=7
          BRANCH_NAME="issue-${ISSUE_NUMBER}"
          git checkout -b $BRANCH_NAME
          echo "Placeholder commit for issue #${ISSUE_NUMBER}" > placeholder.txt
          git add placeholder.txt
          git commit -m "Placeholder commit for issue #${ISSUE_NUMBER}"
          git push origin $BRANCH_NAME

      - name: Create a draft pull request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.create-branch.outputs.branch }}
          title: "Draft PR for issue #${{ github.event.issue.number }}"
          body: "This is a draft pull request for issue #${{ github.event.issue.number }}."
          draft: true

         
