name: Manual Performance Test

on:
  workflow_dispatch:
    inputs:
      test_duration:
        description: 'Test duration in minutes'
        required: true
        default: '10'
      concurrent_users:
        description: 'Number of concurrent users'
        required: true
        default: '50'
      test_environment:
        description: 'Environment to test'
        required: true
        type: choice
        options:
          - staging
          - production

jobs:
  performance-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run performance test
        run: echo "Running performance test for ${{ github.event.inputs.test_duration }} minutes with ${{ github.event.inputs.concurrent_users }} users on ${{ github.event.inputs.test_environment }}"